//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsg_DAL
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    public partial class smsg_MessageThread_Visitor: FastDatabaseQuery.IPropertiesVisitor
    {
    
        
         public string Visited(FastDatabaseQuery.IReceiveVisitor i)
         {
            StringBuilder sb=new StringBuilder();     
            var item=i as smsg_MessageThread;
            if(item == null)
                 throw new ArgumentException("visiting can not convert to  smsg_MessageThread");
    
                string Format="{0}={1};";
                    sb.Append(string.Format(Format,"IDMessageThread",item.IDMessageThread) );
                    sb.Append(string.Format(Format,"IDMessageInitial",item.IDMessageInitial) );
                    sb.Append(string.Format(Format,"IDMessageReply",item.IDMessageReply) );
                    sb.Append(string.Format(Format,"DateInserted",item.DateInserted) );
                    return sb.ToString();
         }
    
    }
}
