//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq.Expressions;
using System.Linq;
using System.Data.Objects;

using FastDatabaseQuery;
using smsg_DAL;

namespace smsg_DAL
{
    [System.Diagnostics.DebuggerDisplayAttribute("smsg_MessageThread_List Count={Count}")]
    public partial class smsg_MessageThread_List : ColList<smsg_MessageThread>
    {
    
    #region FieldNames
    public class fieldNames
    {
            public readonly string IDMessageThread = "IDMessageThread"; 
            public readonly string IDMessageInitial = "IDMessageInitial"; 
            public readonly string IDMessageReply = "IDMessageReply"; 
            public readonly string DateInserted = "DateInserted"; 
        }
    #endregion
    private static readonly fieldNames s_fields =new fieldNames();
    public static fieldNames FieldNames
    {
        get
        {
            return s_fields;
        }
    }
        #region Find
        public void InitFind()
        {
            base.LoadFromDB = new smsg_MessageThread_FindDB(this);			
            //base.FindInCollection = new smsg_MessageThread_Find(this);
        }
        public new smsg_MessageThread_FindDB LoadFromDB
        {
            get
            {
                return base.LoadFromDB as smsg_MessageThread_FindDB;
            }
            set
            {
                base.LoadFromDB = value;
            }
    
        }
        /*
        public new smsg_MessageThread_Find FindInCollection
        {
            get
            {
                return base.FindInCollection as smsg_MessageThread_Find;
            }
            set
            {
                base.FindInCollection = value;
            }
    
        }
        */
        
        
        #endregion
        #region Constructors
        partial void OnInit();
        public smsg_MessageThread_List()
            : base()
            {
                OnInit();
                InitFind();
                base.BeforeSave+=new EventHandler<EventArgs>(smsg_MessageThread_List_BeforeSave);
            }
    
             
             void smsg_MessageThread_List_BeforeSave(object sender, EventArgs e)
                 {
                     var Visitor=new smsg_MessageThread_Visitor();
                     base.Conection.ChangeTracker.DetectChanges();
                     foreach(var item in base.Conection.ChangeTracker.Entries().Where(p => p.State == System.Data.EntityState.Added || p.State == System.Data.EntityState.Deleted || p.State == System.Data.EntityState.Modified))
                     {
                         var obj = item.CurrentValues.ToObject();
                         var rv = obj as smsg_MessageThread;
                         if (rv != null)
                         {
                              Console.WriteLine(rv.Accept(Visitor));
                         }
                         
    
                     }
                    
                 }
    
    
        public smsg_MessageThread_List(IObjectConnection con)
            : base(con)
            {
                OnInit();
                InitFind();
                base.BeforeSave+=new EventHandler<EventArgs>(smsg_MessageThread_List_BeforeSave);
            }
            private smsg_MessageThread_List(ObjectContext con)
            : base(con)
            {
                OnInit();
                InitFind();
                base.BeforeSave+=new EventHandler<EventArgs>(smsg_MessageThread_List_BeforeSave);
            }
        public smsg_MessageThread_List(string con)
            : base()
            {
                OnInit();
                base.Conection =new MessagingDB(con);
                InitFind();
                base.BeforeSave+=new EventHandler<EventArgs>(smsg_MessageThread_List_BeforeSave);
            }
        #endregion
        partial void OnBeginFastDeleteAll();
        public void FastDeleteAll()
        {
            OnBeginFastDeleteAll();
            //TODO: prefix
            ExecuteCommand(@"delete from smsg_MessageThread");
        }
    
        public void ExecuteCommand(string Command){
          base.Conection.Database.ExecuteSqlCommand(Command);
        }
            public void Update_IDMessageThread(long value)
        {
            
            foreach(var item in this)
            {
                //TODO: prefix
                base.Conection.Database.ExecuteSqlCommand("update smsg_MessageThread set IDMessageThread = {0} where (IDMessageThread= {1}) ",value, item.IDMessageThread);
            }
        }
            public void Update_IDMessageInitial(long value)
        {
            
            foreach(var item in this)
            {
                //TODO: prefix
                base.Conection.Database.ExecuteSqlCommand("update smsg_MessageThread set IDMessageInitial = {0} where (IDMessageThread= {1}) ",value, item.IDMessageThread);
            }
        }
            public void Update_IDMessageReply(long value)
        {
            
            foreach(var item in this)
            {
                //TODO: prefix
                base.Conection.Database.ExecuteSqlCommand("update smsg_MessageThread set IDMessageReply = {0} where (IDMessageThread= {1}) ",value, item.IDMessageThread);
            }
        }
            public void Update_DateInserted(System.DateTime value)
        {
            
            foreach(var item in this)
            {
                //TODO: prefix
                base.Conection.Database.ExecuteSqlCommand("update smsg_MessageThread set DateInserted = {0} where (IDMessageThread= {1}) ",value, item.IDMessageThread);
            }
        }
            public void ExecuteCommandForAll<T>(string Command,Func<smsg_MessageThread, T> value)
        {
            foreach(var item in this)
            {
                T val=value(item);
                base.Conection.Database.ExecuteSqlCommand(Command,val);
            }
        }
        public void ExecuteCommandForAll_FormatPK(string Command){
            foreach(var item in this)
            {
                string cmd=string.Format(Command ,"IDMessageThread");
                base.Conection.Database.ExecuteSqlCommand(cmd);
            }
        }
    
    }
}
