//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq.Expressions;
using System.Linq;
using System.Data.Objects;

using FastDatabaseQuery;
using smsg_DAL;

namespace smsg_DAL
{
    [System.Diagnostics.DebuggerDisplayAttribute("smsg_Message_List Count={Count}")]
    public partial class smsg_Message_List : ColList<smsg_Message>
    {
    
    #region FieldNames
    public class fieldNames
    {
            public readonly string IDMessage = "IDMessage"; 
            public readonly string Subject = "Subject"; 
            public readonly string Body = "Body"; 
            public readonly string FromUser = "FromUser"; 
            public readonly string ToUser = "ToUser"; 
            public readonly string DateInserted = "DateInserted"; 
            public readonly string MessageRead = "MessageRead"; 
        }
    #endregion
    private static readonly fieldNames s_fields =new fieldNames();
    public static fieldNames FieldNames
    {
        get
        {
            return s_fields;
        }
    }
        #region Find
        public void InitFind()
        {
            base.LoadFromDB = new smsg_Message_FindDB(this);			
            //base.FindInCollection = new smsg_Message_Find(this);
        }
        public new smsg_Message_FindDB LoadFromDB
        {
            get
            {
                return base.LoadFromDB as smsg_Message_FindDB;
            }
            set
            {
                base.LoadFromDB = value;
            }
    
        }
        /*
        public new smsg_Message_Find FindInCollection
        {
            get
            {
                return base.FindInCollection as smsg_Message_Find;
            }
            set
            {
                base.FindInCollection = value;
            }
    
        }
        */
        
        
        #endregion
        #region Constructors
        partial void OnInit();
        public smsg_Message_List()
            : base()
            {
                OnInit();
                InitFind();
                base.BeforeSave+=new EventHandler<EventArgs>(smsg_Message_List_BeforeSave);
            }
    
             
             void smsg_Message_List_BeforeSave(object sender, EventArgs e)
                 {
                     var Visitor=new smsg_Message_Visitor();
                     base.Conection.ChangeTracker.DetectChanges();
                     foreach(var item in base.Conection.ChangeTracker.Entries().Where(p => p.State == System.Data.EntityState.Added || p.State == System.Data.EntityState.Deleted || p.State == System.Data.EntityState.Modified))
                     {
                         var obj = item.CurrentValues.ToObject();
                         var rv = obj as smsg_Message;
                         if (rv != null)
                         {
                              Console.WriteLine(rv.Accept(Visitor));
                         }
                         
    
                     }
                    
                 }
    
    
        public smsg_Message_List(IObjectConnection con)
            : base(con)
            {
                OnInit();
                InitFind();
                base.BeforeSave+=new EventHandler<EventArgs>(smsg_Message_List_BeforeSave);
            }
            private smsg_Message_List(ObjectContext con)
            : base(con)
            {
                OnInit();
                InitFind();
                base.BeforeSave+=new EventHandler<EventArgs>(smsg_Message_List_BeforeSave);
            }
        public smsg_Message_List(string con)
            : base()
            {
                OnInit();
                base.Conection =new MessagingDB(con);
                InitFind();
                base.BeforeSave+=new EventHandler<EventArgs>(smsg_Message_List_BeforeSave);
            }
        #endregion
        partial void OnBeginFastDeleteAll();
        public void FastDeleteAll()
        {
            OnBeginFastDeleteAll();
            //TODO: prefix
            ExecuteCommand(@"delete from smsg_Message");
        }
    
        public void ExecuteCommand(string Command){
          base.Conection.Database.ExecuteSqlCommand(Command);
        }
            public void Update_IDMessage(long value)
        {
            
            foreach(var item in this)
            {
                //TODO: prefix
                base.Conection.Database.ExecuteSqlCommand("update smsg_Message set IDMessage = {0} where (IDMessage= {1}) ",value, item.IDMessage);
            }
        }
            public void Update_Subject(string value)
        {
            
            foreach(var item in this)
            {
                //TODO: prefix
                base.Conection.Database.ExecuteSqlCommand("update smsg_Message set Subject = {0} where (IDMessage= {1}) ",value, item.IDMessage);
            }
        }
            public void Update_Body(string value)
        {
            
            foreach(var item in this)
            {
                //TODO: prefix
                base.Conection.Database.ExecuteSqlCommand("update smsg_Message set Body = {0} where (IDMessage= {1}) ",value, item.IDMessage);
            }
        }
            public void Update_FromUser(string value)
        {
            
            foreach(var item in this)
            {
                //TODO: prefix
                base.Conection.Database.ExecuteSqlCommand("update smsg_Message set FromUser = {0} where (IDMessage= {1}) ",value, item.IDMessage);
            }
        }
            public void Update_ToUser(string value)
        {
            
            foreach(var item in this)
            {
                //TODO: prefix
                base.Conection.Database.ExecuteSqlCommand("update smsg_Message set ToUser = {0} where (IDMessage= {1}) ",value, item.IDMessage);
            }
        }
            public void Update_DateInserted(System.DateTime value)
        {
            
            foreach(var item in this)
            {
                //TODO: prefix
                base.Conection.Database.ExecuteSqlCommand("update smsg_Message set DateInserted = {0} where (IDMessage= {1}) ",value, item.IDMessage);
            }
        }
            public void Update_MessageRead(bool value)
        {
            
            foreach(var item in this)
            {
                //TODO: prefix
                base.Conection.Database.ExecuteSqlCommand("update smsg_Message set MessageRead = {0} where (IDMessage= {1}) ",value, item.IDMessage);
            }
        }
            public void ExecuteCommandForAll<T>(string Command,Func<smsg_Message, T> value)
        {
            foreach(var item in this)
            {
                T val=value(item);
                base.Conection.Database.ExecuteSqlCommand(Command,val);
            }
        }
        public void ExecuteCommandForAll_FormatPK(string Command){
            foreach(var item in this)
            {
                string cmd=string.Format(Command ,"IDMessage");
                base.Conection.Database.ExecuteSqlCommand(cmd);
            }
        }
    
    }
}
