//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsg_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class smsg_MessageThread: FastDatabaseQuery.IReceiveVisitor
    {
        public string Accept(FastDatabaseQuery.IPropertiesVisitor visit)
            {
                return visit.Visited(this);
            }
        public long IDMessageThread { get; set; }
        public long IDMessageInitial { get; set; }
        public long IDMessageReply { get; set; }
        public System.DateTime DateInserted { get; set; }
    
        public virtual smsg_Message IDMessage_IDMessageInitial { get; set; }
        public virtual smsg_Message IDMessage_IDMessageReply { get; set; }
        public virtual smsg_Message_Archive IDMessageArchive_IDMessageInitial { get; set; }
        public virtual smsg_Message_Archive IDMessageArchive_IDMessageReply { get; set; }
    }
}
