 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq.Expressions;
using System.Data.Objects;
using System.Linq;
using System.Reflection;
using smsg_DAL;
using FastDatabaseQuery;
using System.Data.Entity;

namespace smsg_DAL
{
    //TODO :find a utility for this default class
    
}
