//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsg_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMsgSEntities : DbContext
    {
        public SMsgSEntities()
            : this("name=SMsgSEntities")
        {
    
        }
    
    	public SMsgSEntities(string Con)
            : base(Con)
        {
    		System.Data.Entity.Database.SetInitializer<SMsgSEntities>(new System.Data.Entity.CreateDatabaseIfNotExists<SMsgSEntities>());
    	//System.Data.Entity.Database.SetInitializer<SMsgSEntities>(new System.Data.Entity.DropCreateDatabaseIfModelChanges<SMsgSEntities>());
    	    }
    	partial void OnBeginModelCreating(DbModelBuilder modelBuilder, string prefix,ref bool Continue);
        partial void OnFinishModelCreating (DbModelBuilder modelBuilder, string prefix);
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    		var prefix = System.Configuration.ConfigurationManager.AppSettings["prefixTable"]??"";
    		bool Continue=true;
            OnBeginModelCreating(modelBuilder,prefix, ref Continue);
    		if(!Continue)
    			return;
    
    		//construct default
    		#region smsg_User 
    		modelBuilder.Entity<smsg_User>().ToTable(prefix  + "smsg_User");
    		modelBuilder.Entity<smsg_User>().HasKey(item => item.IDUser);
    
    
    		#endregion
    	
    		OnFinishModelCreating(modelBuilder, prefix);
    		
        }
    
        public DbSet<smsg_User> smsg_User { get; set; }
    }
}
