//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsg_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class smsg_User: FastDatabaseQuery.IReceiveVisitor
    {
        public string Accept(FastDatabaseQuery.IPropertiesVisitor visit)
            {
                return visit.Visited(this);
            }
        public string IDUser { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
    }
}
